name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Run tests
      run: xcodebuild test -project TCA-example.xcodeproj -scheme TCA-example -resultBundlePath TestResults -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13"

    - uses: kishikawakatsumi/xcresulttool@v1.5.0
      with:
        path: TestResults.xcresult
      if: success() || failure()
